perfetto_cmd: Resolve missing O_CREAT mode
external/perfetto/src/perfetto_cmd/perfetto_cmd.ccexternal/perfetto/src/perfetto_cmd/perfetto_cmd.cc:359:65: error: 'open' has superfluous mode bits; missing O_CREAT? [-Werror,-Wuser-defined-warnings]
    fd.reset(open(kTempDropBoxTraceDir, O_TMPFILE | O_RDWR, 0600));